/**
 * W-SLDA Toolkit
 * 
 * This file provides template for processing of wave-functions generated by st-wslda-2d.
 * 
 * Copy this file to your project folder and compile using:
 *    gcc -std=gnu99 st-processwf-1d-template.c -I. -I$WSLDA/hpc-engine -o st-processwf-1d-template -lm -lfftw3
 * 
 * */ 

// Standard libraries
#include <stdlib.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <complex.h>

// W-SLDA Toolkit API
#define CODEDIM 1
#include "wslda_toolkit.h"

int main( int argc , char ** argv ) 
{ 
    // command line
    if(argc!=2)
    {
        printf("Usage: %s prefix\n", argv[0]);
        return( EXIT_FAILURE ) ;        
    }
    
    char *prefix = argv[1];
    printf("# PREFIX FOR FILES: %s\n", prefix);
    
    // lattice settings
    int nx, ny, nz;
    double dx, dy, dz;
    
    // other variables
    int ix, iy, iz, ixyz; // lattice iterators
    int ierr;             // error flag
    char file_name[256];
    double kF, ec, beta;
    double mu[2];
    int nwf;
    
    sprintf(file_name, "%s/wf.info", prefix);
    printf("# READING INFO FILE: %s\n", file_name);
    file_operationl(read_checkpoint_info_pca(file_name, &nwf, &nx, &ny, &nz, &dx, &dy, &dz, &kF, mu, &ec, &beta));

    printf("# LATTICE: %d x %d x %d\n", nx, ny, nz);
    printf("# SPACING: %.2f x %.2f x %.2f\n", dx, dy, dz);
    printf("# VOLUME : %.2f x %.2f x %.2f\n", dx * nx, dy * ny, dz * nz);
    
    // states information for each kz
    int ikyz, iwf;
    double ei, kyz[2];
    double complex *u, *v;
    cppmallocl(u, nx, double complex);
    cppmallocl(v, nx, double complex);
    
    // file pointers 
    FILE *pFile_en, *pFile_kkyz, *pFile_wfu, *pFile_wfv;
    char rname[128];
    sprintf(rname, "%s.qpe", prefix);
    FILE *rFile=fopen(rname,"w");
    
    ikyz=-1;
    while(1)
    {
        ikyz++; // take next file
        
        // read file header
        sprintf(file_name, "%s/wf.%04d.info", prefix, ikyz);
        if(!exists(file_name)) {break;} // no more files to process
        printf("# OPENING: %s\n", file_name);
        file_operationl(read_checkpoint_info_pca(file_name, &nwf, &nx, &ny, &nz, &dx, &dy, &dz, &kF, mu, &ec, &beta));
        
        // open files
        sprintf(file_name, "%s/wf.%04d_en.dat", prefix, ikyz);
        pFile_en = fopen(file_name, "rb");
        if(pFile_en==NULL) {printf("ERROR: Cannot open %s\n", file_name); return( EXIT_FAILURE ) ;}
        sprintf(file_name, "%s/wf.%04d_kkyz.dat", prefix, ikyz);
        pFile_kkyz = fopen(file_name, "rb");
        if(pFile_kkyz==NULL) {printf("ERROR: Cannot open %s\n", file_name); return( EXIT_FAILURE ) ;}
        sprintf(file_name, "%s/wf.%04d_un.wdat", prefix, ikyz);
        pFile_wfu = fopen(file_name, "rb");
        if(pFile_wfu==NULL) {printf("ERROR: Cannot open %s\n", file_name); return( EXIT_FAILURE ) ;}
        sprintf(file_name, "%s/wf.%04d_vn.wdat", prefix, ikyz);
        pFile_wfv = fopen(file_name, "rb");
        if(pFile_wfv==NULL) {printf("ERROR: Cannot open %s\n", file_name); return( EXIT_FAILURE ) ;}
        
        // read wave-functions
        printf("# PROCESSING WF[%d] FOR ikyz=%d\n", nwf, ikyz);
        for (iwf = 0; iwf < nwf; iwf++)
        {
            fread(&ei, sizeof(double), 1, pFile_en);  // eigen energy
            fread(&kyz, sizeof(double), 2, pFile_kkyz); // (ky,kz) value
            fread(u, sizeof(double complex) * nx, 1, pFile_wfu); // u-component
            fread(v, sizeof(double complex) * nx, 1, pFile_wfv); // v-compoment
            
            // normalize
            ixyz = 0;
            for (ix = 0; ix < nx; ix++)
            {
                u[ixyz] /= sqrt(dx);
                v[ixyz] /= sqrt(dx);
                ixyz++;
            }
            
            // integrate |u|^2 and |v|^2
            double u2 = 0.0, v2 = 0.0;
            ixyz = 0;
            for (ix = 0; ix < nx; ix++)
            {
                u2 += (pow(creal(u[ixyz]), 2) + pow(cimag(u[ixyz]), 2)) * dx;
                v2 += (pow(creal(v[ixyz]), 2) + pow(cimag(v[ixyz]), 2)) * dx;
                ixyz++;
            }
            
            double omega=0.05, een; // from input file
            
            if(u2>0.99)
            {
                een=mu[SPINA]+ei;
//                 printf("%6d %12.6f %12.6f %12.6f %12.6f %12.6f\n", iwf, kyz[0], kyz[1], een, u2, v2);
                fprintf(rFile,"u2%03d %12.6f\n", iwf, u2);
                fprintf(rFile,"eu%03d %12.6f\n", iwf, een);
            }
            if(v2>0.99)
            {
                een=mu[SPINB]-ei;
//                 printf("%6d %12.6f %12.6f %12.6f %12.6f %12.6f\n", iwf, kyz[0], kyz[1], een, u2, v2);
                fprintf(rFile,"v2%03d %12.6f\n", iwf, v2);
                fprintf(rFile,"ev%03d %12.6f\n", iwf, een);
            }
        
        }
        
        
        // close files
        fclose(pFile_en);
        fclose(pFile_kkyz);
        fclose(pFile_wfu);
        fclose(pFile_wfv);
        fclose(rFile);
        printf("# RESULT WRITTEN TO %s\n", rname);
    }
    
    /* Arrays will be cleared automatically */
    return( EXIT_SUCCESS ) ;
}
