/**
 * W-DATA format
 * @author Gabriel Wlazlowski, Warsaw University of Technology, 2020
 *
 * Tool for merging wdata sets
 *
 *
 * */

// wdata lib
#include "wdata.h"

// other libs
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <libgen.h>
#include <math.h>
#include <complex.h>

#define cppmallocl(pointer, size, type)                                     \
    if ((pointer = (type *)malloc((size) * sizeof(type))) == NULL)          \
    {                                                                       \
        fprintf(stderr, "error: cannot malloc()! Exiting!\n");              \
        fprintf(stderr, "error: file=`%s`, line=%d\n", __FILE__, __LINE__); \
        return -1;                                                          \
    }

int main(int argc, char **argv)
{
    printf("# WDATA SETS MERGER\n");

    if (argc < 4)
    {
        printf("# Usage:\n#\t%s output_prefix in_prefix_1 in_prefix_2 ...\n", argv[0]);
        printf("# The tool will produce new wdata-set which is merged of (in_prefix_1,in_prefix_2,...) sets.\n");
        return 0;
    }

    // output_prefix.wtxt already exists: break the code
    char out_file_name[512];
    sprintf(out_file_name, "%s.wtxt", argv[1]);
    FILE *out_file;
    if ((out_file = fopen(out_file_name, "r")))
    {
        fclose(out_file);
        printf("ERROR: FILE `%s` EXISTS!\n", argv[1]);
        return 1;
    }


    // FIXME: correct working dirs name
    // char ctmp1[512], ctmp2[512];
    // char basedir[512];
    // getcwd(basedir, 512);
    // strcpy(ctmp1, argv[1]);
    // strcpy(ctmp2, argv[2]);
    // char *indir = dirname(ctmp1);
    // char *outdir = dirname(ctmp2);
    //
    // printf("# WORKING DIR: `%s` --> `%s`\n", indir, outdir);

    //
    // create metadata handler
    wdata_metadata md;
    wdata_metadata mdout;

    // read metadata from file
    int ierr;
    char in_file_name[512];
    sprintf(in_file_name, "%s.wtxt", argv[2]);
    ierr = wdata_parse_metadata_file(in_file_name, &mdout);
    if (ierr != 0)
    {
        printf("# Cannot read metadata file %s!\n", in_file_name);
        return 1;
    }


    mdout.cycles = 0;
    strcpy(mdout.prefix, argv[1]);

    double *data;
    int bdim = wdata_get_blocklength(&mdout); // get block size
    cppmallocl(data, bdim * 3, double);

    int icycle, ivar, i;
    double time = mdout.t0-0.9*mdout.dt, ltime;
    for(i=2; i<argc; i++) // for each file to merge
    {
        // open wdata ser
        sprintf(in_file_name, "%s.wtxt", argv[i]);
        ierr = wdata_parse_metadata_file(in_file_name, &md);
        if (ierr != 0)
        {
            printf("# Cannot read metadata file %s!\n", in_file_name);
            return 1;
        }

        wdata_get_time(&md, 0, &ltime);
        if(ltime>(time+1*0000001*mdout.dt))
        {
            printf("# Last time from previous file [%f] does not match start time [%f] from file %s!\n", time, ltime, in_file_name);
            return 1;
        }
        printf("# WORKING WITH: %s...\n", in_file_name);

        for (icycle = 0; icycle < md.cycles; icycle++)
        {
            wdata_get_time(&md, icycle, &ltime);
            if(ltime-time<0.5*mdout.dt) continue;
            printf("#\tADDING CYCLE %d->%d [time=%f].\n", icycle, mdout.cycles, ltime);
            for (ivar = 0; ivar < md.nvar; ivar++)
            {
                ierr = wdata_read_cycle(&md, md.var[ivar].name, icycle, data);
                if (ierr != 0)
                {
                    printf("# ERROR: Cannot read datablock!\n");
                    return 1;
                }

                ierr = wdata_write_cycle(&mdout, mdout.var[ivar].name, data);
                if (ierr != 0)
                {
                    printf("# ERROR: Cannot write datablock!\n");
                    return 1;
                }
            } // ivar
            wdata_add_cycle(&mdout);
        } // icycle
        wdata_get_time(&mdout, mdout.cycles-1, &time);
    } // i

    // Write new metadata file
    printf("# WRITING NEW METADAFILE: `%s`\n", out_file_name);
    FILE *f = fopen(out_file_name, "w");
    char infoline[1024], infoline2[1024];
    sprintf(infoline, "# Generated by: ");
    for(i=0; i<argc; i++) { sprintf(infoline2, "%s %s", infoline, argv[i]); strcpy(infoline,infoline2); }
    fprintf(f, "%s\n", infoline);
    wdata_print_metadata(&mdout, f);
    fclose(f);

    printf("# DONE.\n");

    return 0;
}
