
void wdata_generic_cut(char *cmdline, char *wtxt, char *outprefix, int start, int stop, int stride)
{
    char ctmp1[512], ctmp2[512];
    char basedir[512];
    getcwd(basedir, 512);
    strcpy(ctmp1, wtxt);
    strcpy(ctmp2, outprefix);
    char *indir = dirname(ctmp1);
    char *outdir = dirname(ctmp2);

    printf("# WORKING DIR: `%s` --> `%s`\n", indir, outdir);

    // create metadata handler
    wdata_metadata md;
    wdata_metadata mdout;

    // read metadata from file
    int ierr;
    printf("# READING FILE: `%s`\n", wtxt);
    ierr = wdata_parse_metadata_file(wtxt, &md);
    if (ierr != 0)
    {
        printf("# Cannot read metadata file!\n");
        exit(1);
    }

    mdout = md;
    mdout.cycles = 0;
    mdout.t0 = md.t0 + md.dt * start;
    mdout.dt = md.dt*stride;
    strcpy(mdout.prefix, basename(outprefix));

    // set working dirs
    wdata_set_working_dir(&md, indir);
    wdata_set_working_dir(&mdout, outdir);
    wdata_clear_database(&mdout);

    double *data;
    int bdim = wdata_get_blocklength(&md); // get block size
    cppmallocl(data, bdim * 3, double);

    printf("# RANGE TO BE PROCESSED: [%d,%d) WITH STRIDE %d\n", start, stop, stride);

    int icycle, ivar;

    if(stop<0) stop=md.cycles+stop; // take from the end

    for (icycle = 0; icycle < md.cycles; icycle++)
        if (icycle >= start && icycle < stop && icycle % stride == 0)
        {
            for (ivar = 0; ivar < md.nvar; ivar++)
            {
                ierr = wdata_read_cycle(&md, md.var[ivar].name, icycle, data);
                if (ierr != 0)
                {
                    printf("# ERROR: Cannot read datablock!\n");
                    exit(1);
                }

                sprintf(mdout.var[ivar].format, "wdat"); // use wdat format
                ierr = wdata_write_cycle(&mdout, mdout.var[ivar].name, data);
                if (ierr != 0)
                {
                    printf("# ERROR: Cannot write datablock!\n");
                    exit(1);
                }
            }
            wdata_add_cycle(&mdout);
        }

    // wtxt
    char file_name[512];
    char file_name2[512];
#ifdef WDATA_SUBSET_MODE
    mdout.ntxt=0; // do not modify txt
#else
    for (ivar = 0; ivar < md.ntxt; ivar++)
    {
        wdata_get_txt_fullname(&md, md.txt[ivar].filename, file_name);
        wdata_get_txt_fullname(&mdout, md.txt[ivar].filename, file_name2);
        copy_txt(file_name, file_name2);
    }
#endif
    // Write new metadata file
    sprintf(file_name, "%s.wtxt", outprefix);
    printf("# WRITING NEW METADAFILE: `%s`\n", file_name);
    FILE *f = fopen(file_name, "w");
    fprintf(f, "# Generated by: %s\n\n", cmdline);
    wdata_print_metadata(&mdout, f);
    fclose(f);

    printf("# DONE.\n");
}


