
// W-SLDA Toolkit
// generated by jdb.py

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
void jdb_message(FILE *stream)
{
    int maxid = 34;
    srand (time(NULL));
    int r = rand() % maxid;
    switch(r)
    {
		case 0:
			wfprintf(stream, "  A chemist walks into a pharmacy and asks the pharmacist,\n");
			wfprintf(stream, "  “Do you have any acetylsalicylic acid?”\n");
			wfprintf(stream, "  “You mean aspirin?” asked the pharmacist.\n");
			wfprintf(stream, "  “That’s it! I can never remember that word.”\n");
			break;
		case 1:
			wfprintf(stream, "  A physicist, a biologist, and a chemist were going to the ocean for the first time.\n");
			wfprintf(stream, "  The physicist saw the ocean and was fascinated by the waves.\n");
			wfprintf(stream, "  He said he wanted to do some research on the fluid dynamics of the waves and walked into the ocean.\n");
			wfprintf(stream, "  Obviously he was drowned and never returned.\n");
			wfprintf(stream, "  The biologist said he wanted to do research on the flora and fauna inside the ocean and walked inside the ocean.\n");
			wfprintf(stream, "  He, too, never returned.\n");
			wfprintf(stream, "  The chemist waited for a long time and afterwards, wrote the observation,\n");
			wfprintf(stream, "  “The physicist and the biologist are soluble in ocean water.”\n");
			break;
		case 2:
			wfprintf(stream, "  A frog telephones the Psychic Hotline.\n");
			wfprintf(stream, "  His Personal Psychic Advisor tells him,\n");
			wfprintf(stream, "  “You are going to meet a beautiful young girl who will want to know everything about you.”\n");
			wfprintf(stream, "  The frog is thrilled!\n");
			wfprintf(stream, "  “This is great! Will I meet her at a party?”\n");
			wfprintf(stream, "  “No,” says his advisor, “in her biology class.”\n");
			break;
		case 3:
			wfprintf(stream, "  A neutron walks into a bar and asks how much for a beer.\n");
			wfprintf(stream, "  The bartender replies, “For you, no charge.”\n");
			break;
		case 4:
			wfprintf(stream, "  Three statisticians go hunting for deer.\n");
			wfprintf(stream, "  They spot one off in the distance.\n");
			wfprintf(stream, "  The first one shoots about a meter too high.\n");
			wfprintf(stream, "  The second one, about a meter too low.\n");
			wfprintf(stream, "  The third one yells, “We got it!”\n");
			break;
		case 5:
			wfprintf(stream, "  “Did you hear oxygen and magnesium got together??”\n");
			wfprintf(stream, "  “OMg!”\n");
			break;
		case 6:
			wfprintf(stream, "  Famous last words from chemists:\n");
			wfprintf(stream, "  1) “And now the taste test…”\n");
			wfprintf(stream, "  2) “And now shake it a bit…”\n");
			wfprintf(stream, "  3) “In which glass was my mineral water?”\n");
			wfprintf(stream, "  4) “This is a completely safe experimental setup.”\n");
			wfprintf(stream, "  5) “Now you can take the protection window away…”\n");
			break;
		case 7:
			wfprintf(stream, "  The doctor tells a woman that she has only six months to live.\n");
			wfprintf(stream, "  He advises her to marry a chemist and move to Toledo.\n");
			wfprintf(stream, "  The woman asks, “Will this cure my illness?”\n");
			wfprintf(stream, "  “No,” replies the doctor, “but it will make six months seem like a very long time.”\n");
			break;
		case 8:
			wfprintf(stream, "  A psychoanalyst shows a patient an inkblot and asks him what he sees.\n");
			wfprintf(stream, "  The patient says: “A man and woman making love.”\n");
			wfprintf(stream, "  The psychoanalyst shows him a second inkblot, and the patient says:\n");
			wfprintf(stream, "  “That’s also a man and woman making love.”\n");
			wfprintf(stream, "  The psychoanalyst says: “You are obsessed with sex.”\n");
			wfprintf(stream, "  The patient says: “What do you mean I’m obsessed? You’re the one with all the dirty pictures.”\n");
			break;
		case 9:
			wfprintf(stream, "  Q: Why can you never trust atoms?\n");
			wfprintf(stream, "  A: They make up everything!\n");
			break;
		case 10:
			wfprintf(stream, "  Q: What was the name of the first Electricity Detective?\n");
			wfprintf(stream, "  A: Sherlock Ohms.\n");
			break;
		case 11:
			wfprintf(stream, "  One tectonic plate bumped into another and said:\n");
			wfprintf(stream, "  “Sorry, my fault.”\n");
			break;
		case 12:
			wfprintf(stream, "  A biologist, an engineer, and a mathematician were observing an empty building.\n");
			wfprintf(stream, "  They noted two people entering the building and sometime later observed three coming out.\n");
			wfprintf(stream, "  The biologist remarked, “Oh, they must have reproduced.”\n");
			wfprintf(stream, "  The engineer said, “Our initial count must have been incorrect.”\n");
			wfprintf(stream, "  The mathematician stated, “Now if one more person goes into the building, it will be completely empty.”\n");
			break;
		case 13:
			wfprintf(stream, "  They have just found the gene for shyness.\n");
			wfprintf(stream, "  They would have found it earlier, but it was hiding behind two other genes.\n");
			break;
		case 14:
			wfprintf(stream, "  Science is a wonderful thing if one does not have to earn one\'s living at it.\n");
			wfprintf(stream, "  -- Albert Einstein --\n");
			break;
		case 15:
			wfprintf(stream, "  Only two things are infinite, the universe and human stupidity, and I\'m not sure about the former.\n");
			wfprintf(stream, "  -- Albert Einstein --\n");
			break;
		case 16:
			wfprintf(stream, "  Science is the great antidote to the poison of enthusiasm and superstition.\n");
			wfprintf(stream, "  -- Adam Smith --\n");
			break;
		case 17:
			wfprintf(stream, "  To steal ideas from one person is plagiarism; to steal from many is research.\n");
			wfprintf(stream, "  -- Steven Wright --\n");
			break;
		case 18:
			break;
		case 19:
			wfprintf(stream, "  If we knew what it was we were doing, it would not be called research, would it?\n");
			wfprintf(stream, "  -- Albert Einstein --\n");
			break;
		case 20:
			wfprintf(stream, "  In the beginning the Universe was created.\n");
			wfprintf(stream, "  This has made a lot of people very angry and been widely regarded as a bad move.\n");
			wfprintf(stream, "  -- Douglas Adams --\n");
			break;
		case 21:
			wfprintf(stream, "  If you torture the data long enough, it will confess.\n");
			wfprintf(stream, "  -- Ronald Coase --\n");
			break;
		case 22:
			wfprintf(stream, "  Science can never solve one problem without raising ten more problems.\n");
			wfprintf(stream, "  -- George Bernard Shaw --\n");
			break;
		case 23:
			wfprintf(stream, "  Science does not know its debt to imagination.\n");
			wfprintf(stream, "  -- Ralph Waldo Emerson --\n");
			break;
		case 24:
			wfprintf(stream, "  The most exciting phrase to hear in science, the one that heralds new discoveries,\n");
			wfprintf(stream, "  is not \'Eureka!\' but \'That\'s funny...\'\n");
			wfprintf(stream, "  -- Isaac Asimov --\n");
			break;
		case 25:
			wfprintf(stream, "  The great tragedy of science - the slaying of a beautiful hypothesis by an ugly fact.\n");
			wfprintf(stream, "  -- Thomas Huxley --\n");
			break;
		case 26:
			wfprintf(stream, "  I have had my results for a long time: but I do not yet know how I am to arrive at them.\n");
			wfprintf(stream, "  -- Carl Friedrich Gauss --\n");
			break;
		case 27:
			wfprintf(stream, "  I\'m sure the universe is full of intelligent life. It\'s just been too intelligent to come here.\n");
			wfprintf(stream, "  -- Arthur C. Clarke --\n");
			break;
		case 28:
			wfprintf(stream, "  In physics, you don\'t have to go around making trouble for yourself - nature does it for you.\n");
			wfprintf(stream, "  -- Frank Wilczek --\n");
			break;
		case 29:
			wfprintf(stream, "  Computers are useless. They can only give you answers.\n");
			wfprintf(stream, "  -- Pablo Picasso --\n");
			break;
		case 30:
			wfprintf(stream, "  Once you can accept the universe as matter expanding into nothing that is something,\n");
			wfprintf(stream, "  wearing stripes with plaid comes easy.\n");
			wfprintf(stream, "  -- Albert Einstein --\n");
			break;
		case 31:
			wfprintf(stream, "  Molecular biology is essentially the practice of biochemistry without a license.\n");
			wfprintf(stream, "  -- Erwin Chargaff --\n");
			break;
		case 32:
			wfprintf(stream, "  There is a theory which states that if ever anyone discovers exactly\n");
			wfprintf(stream, "  what the Universe is for and why it is here, it will instantly disappear\n");
			wfprintf(stream, "  and be replaced by something even more bizarre and inexplicable.\n");
			wfprintf(stream, "  There is another theory which states that this has already happened.\n");
			wfprintf(stream, "  -- Douglas Adams --\n");
			break;
		case 33:
			wfprintf(stream, "  Programming today is a race between software engineers striving\n");
			wfprintf(stream, "  to build bigger and better idiot-proof programs, and the Universe trying\n");
			wfprintf(stream, "  to produce bigger and better idiots. So far, the Universe is winning.\n");
			wfprintf(stream, "  -- Rick Cook --\n");

        default: break;
    }
}

