#!/usr/bin/python

# W-SLDA Toolkit
# @author Gabriel Wlazlowski

from string import *
import sys
import os


targetfile="jdb.h"
fin="jdb.txt"

src = open(fin, "r")
entries=0
for line in src:
    line = line.strip()
    if line=="": entries=entries+1
src.close()

print "Number of entries in jdb.txt: ", entries


header = """
// W-SLDA Toolkit
// generated by jdb.py

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
void jdb_message(FILE *stream)
{
    int maxid = %d;
    srand (time(NULL));
    int r = rand() %% maxid;
    switch(r)
    {
"""
footer="""
        default: break;
    }
}

"""


# create file
f = open(targetfile, "w")
f.write(header % entries)
src = open(fin, "r")
addbreak = False 
i=0;
for line in src:
    line = line.strip()
    line = line.replace("\n", "")
    line = line.replace("\\", "\\\\")
    line = line.replace("\"", "\\\"")
    line = line.replace("\'", "\\\'")
    line = line.replace("%", "%%")
    
    if len(line)>0 and line[0]=='#': 
        continue
    
    if line=="":
        if addbreak: 
            f.write('\t\t\tbreak;\n')
        f.write('\t\tcase %d:\n' % i)
        i = i+1
        addbreak=True
        continue
        
    f.write('\t\t\twfprintf(stream, "  %s\\n");\n' % line)
src.close()

f.write(footer)
# close file
f.close()
