/**
 * W-SLDA Toolkit
 * Author: Gabriel Wlazlowski
 * Creation date: 31-07-2020
 * */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <complex.h>

#include "wdata.h"

#include "pca_settings.h"
#include "pca_utils.h"
#include <mpi.h>
/**
 * @param input input structure (INPUT)
 * @param datadim data dimensonality (INPUT)
 * @param t0 initial  value of time
 * @param dt time increment between measurments
 * @param spinsymmetry flag inicating if system is spin-symmetric
 * @param wdmd metadata for wdata format (OUTPUT)
 * @return exit status 0: ok, 
 * */
int create_wdata_metadata(metadata_t *input, int datadim, double t0, double dt, int spinsymmetry, wdata_metadata *wdmd)
{
    // create artificial data for visulisation in visit
    wdata_metadata tmd = {NX, NY, NZ, DX, DY, DZ, 0, "none", 0, 0.0, 0.0, 0, 0};
    tmd.datadim=datadim;
    sprintf(tmd.prefix, "%s", md.outprefix);
    tmd.t0=t0;
    tmd.dt=dt;
    
    // add variables
    int lnvars;
    char lvars[MAX_WRITEVARS][MAX_VARNAME_LGTH]; // and their names
    int i;
    
    // simple copy of variables to list
    lnvars = md.nwritevar;
    for(i=0; i<lnvars; i++) strcpy(lvars[i],md.writevar[i]);
    
    for(i=0; i<lnvars; i++)
    {        
        if(strcmp (lvars[i],"density") == 0)
        {
            wdata_variable va = {"density_a", "real", "none"};
            wdata_variable vb = {"density_b", "real", "none"};
            wdata_link l = {"density_b", "density_a"};
            wdata_add_variable(&tmd, &va);
            if(spinsymmetry==0) wdata_add_variable(&tmd, &vb);
            else                wdata_add_link(&tmd, &l);
        }
        else if(strcmp (lvars[i],"current") == 0)
        {
            wdata_variable va = {"current_a", "vector", "none"};
            wdata_variable vb = {"current_b", "vector", "none"};
            wdata_link l = {"current_b", "current_a"};
            wdata_add_variable(&tmd, &va);
            if(spinsymmetry==0) wdata_add_variable(&tmd, &vb);
            else                wdata_add_link(&tmd, &l);
        }
        else if(strcmp (lvars[i],"tau") == 0)
        {
            wdata_variable va = {"tau_a", "real", "none"};
            wdata_variable vb = {"tau_b", "real", "none"};
            wdata_link l = {"tau_b", "tau_a"};
            wdata_add_variable(&tmd, &va);
            if(spinsymmetry==0) wdata_add_variable(&tmd, &vb);
            else                wdata_add_link(&tmd, &l);
        }
        else if(strcmp (lvars[i],"U") == 0)
        {
            wdata_variable va = {"U_a", "real", "none"};
            wdata_variable vb = {"U_b", "real", "none"};
            wdata_link l = {"U_b", "U_a"};
            wdata_add_variable(&tmd, &va);
            if(spinsymmetry==0) wdata_add_variable(&tmd, &vb);
            else                wdata_add_link(&tmd, &l);
        }
        else if(strcmp (lvars[i],"v_ext") == 0)
        {
            wdata_variable va = {"v_ext_a", "real", "none"};
            wdata_variable vb = {"v_ext_b", "real", "none"};
            wdata_link l = {"v_ext_b", "v_ext_a"};
            wdata_add_variable(&tmd, &va);
            if(spinsymmetry==0) wdata_add_variable(&tmd, &vb);
            else                wdata_add_link(&tmd, &l);
        }
        else if(strcmp (lvars[i],"velocity_ext") == 0)
        {
            wdata_variable va = {"velocity_ext_a", "real", "none"};
            wdata_variable vb = {"velocity_ext_b", "real", "none"};
            wdata_link l = {"velocity_ext_b", "velocity_ext_a"};
            wdata_add_variable(&tmd, &va);
            if(spinsymmetry==0) wdata_add_variable(&tmd, &vb);
            else                wdata_add_link(&tmd, &l);
        }
        else if(strcmp (lvars[i],"delta") == 0)
        {
            wdata_variable va = {"delta", "complex", "none"};
            wdata_add_variable(&tmd, &va);
        }
        else if(strcmp (lvars[i],"nu") == 0)
        {
            wdata_variable va = {"nu", "complex", "none"};
            wdata_add_variable(&tmd, &va);
        }
        
    }
    
    *wdmd = tmd; // copy to output buffers
    return 0;
}

/**
 * @return 1 in case if files cannot be deleted (mainly due to overwrite=0)
 * */
int clear_files(metadata_t *input, wdata_metadata *wdmd)
{
    int i;
    if(md.overwrite==0) for(i=0; i<wdmd->nvars; i++) if(wdata_file_exists(wdmd,wdmd->vars[i].name)) return 1;
    
    wdata_clear_database(wdmd);
    
    return 0;
}

int write_wdata_metadata_file(metadata_t *input, wdata_metadata *wdmd, char *codename)
{
    char file_name[256];
    sprintf(file_name, "%s.wtxt", md.outprefix);
    FILE *f = fopen(file_name, "w");
    if(f==NULL) return 1;
    
    time_t rawtime;
    struct tm * timeinfo;
    char buffer [20];
    time ( &rawtime );
    timeinfo = localtime ( &rawtime );
    strftime (buffer,20,"%x-%X",timeinfo);
    
    fprintf(f,"# Generated by %s [%s]\n\n", codename, buffer);
    wdata_print_metadata(wdmd, f);
    
    fclose(f);
    
    return 0;
}

/**
 * Writes measurements
 * @param wdmd metadata for wdata format
 * @param mpi_comm mpi communicator: function utilizes parrallel method of writing
 * @param codetype "st" - static code, "td" - timependent code 
 * @param h_densities array of densities
 * @param h_potentials array of potentials
 * @param h_potentials_ext array of external potentials
 * @return 0: ok, otherwise error
 * */
int write_measurments(wdata_metadata *wdmd, MPI_Comm mpi_comm, char *codetype, double *h_densities, double *h_potentials, double *h_potentials_ext)
{
    int iam, np;
    MPI_Comm_size( mpi_comm , &np ) ; /* total number of processes */
    MPI_Comm_rank( mpi_comm , &iam ) ; /* id of process st 0 <= iam < np */    
    
    double *rho_a;
    double *rho_b;
    double *tau_a;
    double *tau_b;
    double complex *nu;
    double *j_a_x;
    double *j_a_y;
    double *j_a_z;
    double *j_b_x;
    double *j_b_y;
    double *j_b_z;
    
    // pontentials
    double *V_a;
    double *V_b;
    double complex *delta;

    if (strcmp (codetype,"st") == 0)
    {
        rho_a = (double *)(h_densities +  0*NX*NY);
        rho_b = (double *)(h_densities +  1*NX*NY);
        tau_a = (double *)(h_densities +  2*NX*NY);
        tau_b = (double *)(h_densities +  3*NX*NY);
        nu = (double complex *)(h_densities +  4*NX*NY);
        j_a_x = (double *)(h_densities +  6*NX*NY);
        j_a_y = (double *)(h_densities +  7*NX*NY);
        j_a_z = (double *)(h_densities +  8*NX*NY);
        j_b_x = (double *)(h_densities +  9*NX*NY);
        j_b_y = (double *)(h_densities + 10*NX*NY);
        j_b_z = (double *)(h_densities + 11*NX*NY);
        
        // pontentials
        V_a = (double *)(h_potentials +  0*NX*NY);
        V_b = (double *)(h_potentials +  1*NX*NY);
        delta = (double complex *)(h_potentials +  2*NX*NY);
    }
    else if (strcmp (codetype,"td") == 0)
    {
        // TODO
        return -2;
    }
    else return -1;
    
    // write variables
    int ivar, ierr;
    for(ivar=0; ivar<wdmd->nvars; ivar++) if(ivar%np == iam) // each process handles different variable
    {
        ierr=0;
        if      (strcmp (wdmd->vars[ivar].name,"density_a") == 0) ierr = wdata_write_cycle(wdmd, "density_a", rho_a);
        else if (strcmp (wdmd->vars[ivar].name,"density_b") == 0) ierr = wdata_write_cycle(wdmd, "density_b", rho_b);
        else if (strcmp (wdmd->vars[ivar].name,"delta") == 0) ierr = wdata_write_cycle(wdmd, "delta", delta);
        else if (strcmp (wdmd->vars[ivar].name,"current_a") == 0) ierr = wdata_write_cycle(wdmd, "current_a", j_a_x);
        else if (strcmp (wdmd->vars[ivar].name,"current_b") == 0) ierr = wdata_write_cycle(wdmd, "current_b", j_b_x);
        else if (strcmp (wdmd->vars[ivar].name,"nu") == 0) ierr = wdata_write_cycle(wdmd, "nu", nu);
        else if (strcmp (wdmd->vars[ivar].name,"tau_a") == 0) ierr = wdata_write_cycle(wdmd, "tau_a", tau_a);
        else if (strcmp (wdmd->vars[ivar].name,"tau_b") == 0) ierr = wdata_write_cycle(wdmd, "tau_b", tau_b);
        else if (strcmp (wdmd->vars[ivar].name,"U_a") == 0) ierr = wdata_write_cycle(wdmd, "U_a", V_a);
        else if (strcmp (wdmd->vars[ivar].name,"U_b") == 0) ierr = wdata_write_cycle(wdmd, "U_b", V_b);
        
        if(ierr>0) return 100*iam+10*ivar+ierr;
    }
    
    // cycle is complete
    wdata_add_cycle(wdmd);
    
    return 0;
}

