/*****************************************************************************
// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.
*****************************************************************************/

// ************************************************************************* //
//                            avtwdataFileFormat.h                           //
// ************************************************************************* //

#ifndef AVT_wdata_FILE_FORMAT_H
#define AVT_wdata_FILE_FORMAT_H

#include <avtMTSDFileFormat.h>

#include <vector>
#include <complex>

typedef std::complex<float> Complex;

#include "wdata.h"

// ****************************************************************************
//  Class: wdataVariable
//
//  Purpose:
//
//  Programmer: gabrielw
//  Creation:   Wed Jul 29 19:18:00 PST 2020
//
//  Modifications:
//    Kathleen Biagas, Wed Sept 22, 2021
//    Have getVariable, isScalar and isVector return false to fix compile error
//    on Windows.  Cast numberOfVariables return to int. Remove unneeded ';'.
//
//    Gabriel Wlazlowski, Jul 03, 2025
//    Update of plugin to be compatible with WData format version 0.3.0
// ****************************************************************************

class wdataVariable
{
public:
    wdataVariable(wdata_metadata *wdmd, int varid, int precdowngrade);
    virtual ~wdataVariable() { ; }

    virtual bool getVariable(const char *_varname, int cycleid, float *data_for_visit) { return false; }

    int numberOfVariables() { return int(varname.size()); }
    std::string getIthVariableName(int ith) { return varname[ith]; }
    std::string getIthVariableUnit(int ith) { return varunit[ith]; }

    virtual bool isScalar() { return false; }
    virtual bool isVector() { return false; }

protected:
    int loadCycle(int cycleid);

    int vid;            // index of varaiable in md->vars table
    int d2f;            // downgrade double to float
    wdata_metadata *md; // variable info
    int loadedcycle;

    void *data; // each varaiable has data

    std::vector<std::string> varname; // list of var names that can be generated from this variable
    std::vector<std::string> varunit; // corresponding units
};

class wdataRealVariable : public wdataVariable
{
public:
    wdataRealVariable(wdata_metadata *wdmd, int varid, int precdowngrade);
    ~wdataRealVariable() { free(data); };

    bool getVariable(const char *_varname, int cycleid, float *data_for_visit);

    bool isScalar() { return true; };
    bool isVector() { return false; };

protected:
    float *dataR;
};

enum cplxtrans
{
    cabs,
    carg,
    cre,
    cim
};
class wdataComplexVariable : public wdataVariable
{
public:
    wdataComplexVariable(wdata_metadata *wdmd, int varid, int precdowngrade);
    ~wdataComplexVariable() { free(data); };

    bool getVariable(const char *_varname, int cycleid, float *data_for_visit);

    bool isScalar() { return true; };
    bool isVector() { return false; };

protected:
    Complex *dataC;
    std::vector<cplxtrans> trans; // transformations
};

class wdataVectorVariable : public wdataVariable
{
public:
    wdataVectorVariable(wdata_metadata *wdmd, int varid, int precdowngrade, int dim);
    ~wdataVectorVariable() { free(data); };

    bool getVariable(const char *_varname, int cycleid, float *data_for_visit);

    bool isScalar() { return false; };
    bool isVector() { return true; };

protected:
    int vdim;
    float *dataVx;
    float *dataVy;
    float *dataVz;
};

// ****************************************************************************
//  Class: avtwdataFileFormat
//
//  Purpose:
//      Reads in wdata files as a plugin to VisIt.
//
//  Programmer: gabrielw -- generated by xml2avt
//  Creation:   Wed Jul 29 19:18:00 PST 2020
//
// ****************************************************************************

class avtwdataFileFormat : public avtMTSDFileFormat
{
public:
    avtwdataFileFormat(const char *);
    virtual ~avtwdataFileFormat();

    //
    // This is used to return unconvention data -- ranging from material
    // information to information about block connectivity.
    //
    // virtual void      *GetAuxiliaryData(const char *var, int timestep,
    //                                     const char *type, void *args,
    //                                     DestructorFunction &);
    //

    //
    // If you know the times and cycle numbers, overload this function.
    // Otherwise, VisIt will make up some reasonable ones for you.
    //
    virtual void GetCycles(std::vector<int> &);
    virtual void GetTimes(std::vector<double> &);

    virtual int GetNTimesteps(void);

    virtual const char *GetType(void) { return "wdata"; };
    virtual void FreeUpResources(void);

    virtual vtkDataSet *GetMesh(int, const char *);
    virtual vtkDataArray *GetVar(int, const char *);
    virtual vtkDataArray *GetVectorVar(int, const char *);

protected:
    // DATA MEMBERS

    wdata_metadata wdmd;

    virtual void PopulateDatabaseMetaData(avtDatabaseMetaData *, int);

    std::vector<wdataVariable *> variable;

    std::string dbcomment;
};

#endif
