// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: wdataPluginInfo.C
// ****************************************************************************

#include <wdataPluginInfo.h>

#include <visit-config.h>
VISIT_PLUGIN_VERSION(wdata,DBP_EXPORT)

VISIT_DATABASE_PLUGIN_ENTRY(wdata,General)

// ****************************************************************************
//  Method: wdataGeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the database plugin.
//
//  Returns:    A pointer to the name of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
wdataGeneralPluginInfo::GetName() const
{
    return "wdata";
}

// ****************************************************************************
//  Method: wdataGeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the database plugin.
//
//  Returns:    A pointer to the version of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
wdataGeneralPluginInfo::GetVersion() const
{
    return "0.3.0";
}

// ****************************************************************************
//  Method: wdataGeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the database plugin.
//
//  Returns:    A pointer to the id of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
wdataGeneralPluginInfo::GetID() const
{
    return "wdata_0.3.0";
}
// ****************************************************************************
//  Method: wdataGeneralPluginInfo::EnabledByDefault
//
//  Purpose:
//    Return true if this plugin should be enabled by default; false otherwise.
//
//  Returns:    true/false
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

bool
wdataGeneralPluginInfo::EnabledByDefault() const
{
    return true;
}
// ****************************************************************************
//  Method: wdataGeneralPluginInfo::HasWriter
//
//  Purpose:
//    Return true if this plugin has a database writer.
//
//  Returns:    true/false
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

bool
wdataGeneralPluginInfo::HasWriter() const
{
    return false;
}
// ****************************************************************************
//  Method:  wdataGeneralPluginInfo::GetDefaultFilePatterns
//
//  Purpose:
//    Returns the default patterns for a wdata database.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
std::vector<std::string>
wdataGeneralPluginInfo::GetDefaultFilePatterns() const
{
    std::vector<std::string> defaultPatterns;
    defaultPatterns.push_back("*.wtxt");

    return defaultPatterns;
}

// ****************************************************************************
//  Method:  wdataGeneralPluginInfo::AreDefaultFilePatternsStrict
//
//  Purpose:
//    Returns if the file patterns for a wdata database are
//    intended to be interpreted strictly by default.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
bool
wdataGeneralPluginInfo::AreDefaultFilePatternsStrict() const
{
    return false;
}

// ****************************************************************************
//  Method:  wdataGeneralPluginInfo::OpensWholeDirectory
//
//  Purpose:
//    Returns if the wdata plugin opens a whole directory name
//    instead of a single file.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
bool
wdataGeneralPluginInfo::OpensWholeDirectory() const
{
    return false;
}
