// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <wdataPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(wdata,Engine)

// ****************************************************************************
//  Method: wdataEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a wdata writer.
//
//  Returns:    A wdata writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
wdataEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

