
# COMPILER
CXX=mpicc

# DIRECTORY SETTINGS
OBJDIR=./obj/
BINDIR=./
WSLDADIR=../hpc-engine/
WDATADIR=../lib-wdata/
# COMPILER FLAGS
CFLAGS= -std=gnu99 -O3  -I/usr/local/include/elpa-2018.11.001
# LIBS=-lfftw3 -lm -llapack -L/usr/lib64/openmpi/lib -lscalapack 
LIBS=-lfftw3 -lm -llapack -L/usr/lib64/openmpi/lib -lscalapack -L/usr/local/lib/ -lelpa

include mk.st
 
