/**
 * W-SLDA Toolkit
 * 
 * This file demonstrates how to compute momentum distribution from data generated by st-wslda-2d.
 * 
 * Copy this file to your project folder and compile using:
 *    gcc -std=gnu99 st-processwf-nk-2d.c -I. -I$WSLDA/hpc-engine -o st-processwf-nk-2d -lm -lfftw3
 * 
 * */ 

// Standard libraries
#include <stdlib.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <complex.h>

// W-SLDA Toolkit API
#include "wslda_toolkit.h"

#include <fftw3.h>

int main( int argc , char ** argv ) 
{ 
    // command line
    if(argc!=2)
    {
        printf("Usage: %s prefix\n", argv[0]);
        return( EXIT_FAILURE ) ;        
    }
    
    char *prefix = argv[1];
    printf("# PREFIX FOR FILES: %s\n", prefix);
    
    // lattice settings
    int nx, ny, nz;
    double dx, dy, dz;
    
    // other variables
    int ix, iy, iz, ixyz; // lattice iterators
    int ierr;             // error flag
    char file_name[256];
    double kF, ec, beta;
    double mu[2];
    int nwf;
    
    sprintf(file_name, "%s/s2dpca.info", prefix);
    printf("# READING INFO FILE: %s\n", file_name);
    file_operationl(read_checkpoint_info_pca(file_name, &nwf, &nx, &ny, &nz, &dx, &dy, &dz, &kF, mu, &ec, &beta));

    printf("# LATTICE: %d x %d x %d\n", nx, ny, nz);
    printf("# SPACING: %.2f x %.2f x %.2f\n", dx, dy, dz);
    printf("# VOLUME : %.2f x %.2f x %.2f\n", dx * nx, dy * ny, dz * nz);
    
    // states information for each kz
    int ikz, iwf;
    double ei, kz;
    double complex *u, *v;
    cppmallocl(u, nx * ny, double complex);
    cppmallocl(v, nx * ny, double complex);

    fftw_plan plan_f_v = fftw_plan_dft_2d(nx, ny, v, v, FFTW_FORWARD, FFTW_ESTIMATE);
    fftw_plan plan_f_u = fftw_plan_dft_2d(nx, ny, u, u, FFTW_FORWARD, FFTW_ESTIMATE);

    // buffers for momentum distribution
    double *nk_a, *nk_b;
    cppmallocl(nk_a, nx * ny, double);
    cppmallocl(nk_b, nx * ny, double);
    for(ixyz=0; ixyz<nx*ny; ixyz++) nk_a[ixyz]=0.0;
    for(ixyz=0; ixyz<nx*ny; ixyz++) nk_b[ixyz]=0.0;

    // file pointers 
    FILE *pFile_en, *pFile_kkz, *pFile_wfu, *pFile_wfv;
    
    // for (ikz = 0; ikz < nz / 2; ikz++) // do for all values of momentum
    ikz=0; // do only for kz=0.0
    {
        // read file header
        sprintf(file_name, "%s/s2dpca.%04d.info", prefix, ikz);
        printf("# OPENING: %s\n", file_name);
        file_operationl(read_checkpoint_info_pca(file_name, &nwf, &nx, &ny, &nz, &dx, &dy, &dz, &kF, mu, &ec, &beta));
        
        // open files
        sprintf(file_name, "%s/s2dpca.%04d.en", prefix, ikz);
        pFile_en = fopen(file_name, "rb");
        if(pFile_en==NULL) {printf("ERROR: Cannot open %s\n", file_name); return( EXIT_FAILURE ) ;}
        sprintf(file_name, "%s/s2dpca.%04d.kkz", prefix, ikz);
        pFile_kkz = fopen(file_name, "rb");
        if(pFile_en==NULL) {printf("ERROR: Cannot open %s\n", file_name); return( EXIT_FAILURE ) ;}
        sprintf(file_name, "%s/s2dpca.%04d.wfu", prefix, ikz);
        pFile_wfu = fopen(file_name, "rb");
        if(pFile_en==NULL) {printf("ERROR: Cannot open %s\n", file_name); return( EXIT_FAILURE ) ;}
        sprintf(file_name, "%s/s2dpca.%04d.wfv", prefix, ikz);
        pFile_wfv = fopen(file_name, "rb");
        if(pFile_en==NULL) {printf("ERROR: Cannot open %s\n", file_name); return( EXIT_FAILURE ) ;}
        
        // read wave-functions
        printf("# PROCESSING WF[%d] FOR ikz=%d\n", nwf, ikz);
        for (iwf = 0; iwf < nwf; iwf++)
        {
            fread(&ei, sizeof(double), 1, pFile_en);  // eigen energy
            fread(&kz, sizeof(double), 1, pFile_kkz); // kz value
            fread(u, sizeof(double complex) * nx * ny, 1, pFile_wfu); // u-component
            fread(v, sizeof(double complex) * nx * ny, 1, pFile_wfv); // v-compoment
            
            // normalize
            ixyz = 0;
            for (ix = 0; ix < nx; ix++) for (iy = 0; iy < ny; iy++)
            {
                u[ixyz] /= sqrt(dx * dy);
                v[ixyz] /= sqrt(dx * dy);
                ixyz++;
            }

            // go to momentum space
            // execute the plan for v ...
            fftw_execute(plan_f_v);
            for(ixyz=0; ixyz<nx*ny; ixyz++) v[ixyz]*=dx*dy; // missing volume element
            // ... and for u
            fftw_execute(plan_f_u);
            for(ixyz=0; ixyz<nx*ny; ixyz++) u[ixyz]*=dx*dy; // missing volume element

            
            // add contribution to the density number
            double w=1.;
            if(ikz>0) w=2.0; // take into account that contributions from +kz and -kz are the same

            for(ixyz=0; ixyz<nx*ny; ixyz++)
            {
                nk_a[ixyz]+=w*pow(cabs(u[ixyz]),2)*fbeta( ei, beta)/(dx * nx* dy * ny);
                nk_b[ixyz]+=w*pow(cabs(v[ixyz]),2)*fbeta(-ei, beta)/(dx * nx* dy * ny);
            }
        }
        
        
        // close files
        fclose(pFile_en);
        fclose(pFile_kkz);
        fclose(pFile_wfu);
        fclose(pFile_wfv);
    }

    // test particle number
    double N_a=0.0, N_b=0.0;
    for(ixyz=0; ixyz<nx*ny; ixyz++) N_a+=nk_a[ixyz];
    for(ixyz=0; ixyz<nx*ny; ixyz++) N_b+=nk_b[ixyz];
    printf("# N_a=%f, N_b=%f\n", N_a, N_b);

    // Simple printing of momentum distribution for n(kx, ky=0.0, ...)
    ixyz=0;
    for(ix=0; ix<nx; ix++) for(iy=0; iy<ny; iy++)
    {
        double kx,ky;
        if(ix<nx/2) kx=2.*M_PI/(dx*nx) * ( double )(ix   );
        else        kx=2.*M_PI/(dx*nx) * ( double )(ix-nx);

        if(iy<ny/2) ky=2.*M_PI/(dy*ny) * ( double )(iy   );
        else        ky=2.*M_PI/(dy*ny) * ( double )(iy-ny);

        if(fabs(ky)<0.01) printf("%8.4f %8.4f %9.6f %9.6f\n", kx, ky, nk_a[ixyz], nk_b[ixyz]);

        ixyz++;
    }


    /* Arrays will be cleared automatically */
    return( EXIT_SUCCESS ) ;
}
